# Generated by Django 3.0.6 on 2020-08-27 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KZzone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('zone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RUSzone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('zone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('from_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.KZzone')),
                ('to_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.RUSzone')),
            ],
        ),
    ]
